apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: kubearmor-collector
  namespace: kube-system
    #namespace: kubearmor
spec:
  image: kubearmor/otel-receiver:latest
  mode: daemonset
  imagePullPolicy: Always
  config: |
    receivers:
      kubearmor_receiver:
        endpoint: ${env:KUBEARMOR_SERVICE?default=kubearmor:32767}
        logfilter: ${env:LOGFILTER?default=all}

    exporters:
      logging:
        verbosity: detailed
      loki:
        endpoint: "http://loki.default.svc:3100/loki/api/v1/push"
    processors:
      filter/ottl:
        error_mode: ignore
        logs:
          log_record:
          - 'not (IsMatch(body, ".*Permission denied.*"))'
    service:
      pipelines:
        logs:
          receivers:
            - kubearmor_receiver
          processors:
            - filter/ottl
          exporters:
            - loki
            - logging
  env:
  - name: KUBEARMOR_SERVICE
    value: kubearmor:32767
