apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: kubearmor-collector
  namespace: kubearmor
spec:
  image: kubearmor/otel-adapter:latest
  imagePullPolicy: Always
  config: |
    receivers:
      kubearmor_receiver:
        endpoint: kubearmor:32767 # Please update this if you install collector in a seperate namespace
        logfilter: all
    exporters:
      logging:
        verbosity: detailed
      loki:
        endpoint: "http://loki.default.svc:3100/loki/api/v1/push"

    service:
      pipelines:
        logs:
          receivers:
            - kubearmor_receiver
          processors: []
          exporters:
            - loki
            - logging
