{
 "title": "KubeArmor",
 "description": "Charts for kubearmor logs",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "attribute", "label": "Log Attribute", "query": "Level" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"} | json | __error__=``"
    }
   ]
  },
  {
   "title": "Visual representation of log in a table",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\"}"
    }
   ]
  },
  {
   "title": "Visual representation of log $attribute in a guage",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "repeat": "attribute",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(label) (count_over_time({exporter=\"OTLP\"} |= `` | json label=\"body.$attribute\" | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Visual representation of log $attribute in a pie chart",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "repeat": "attribute",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(label) (count_over_time({exporter=\"OTLP\"} | json label=\"body.$attribute\" | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Occurence of unique values in log $attribute",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(body_$attribute) (count_over_time({exporter=\"OTLP\"} |= `` | json | __error__=`` [$__range]))"
    }
   ]
  },
  {
   "title": "Visual representation of log $attribute in a bar guage",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(logLevel) (count_over_time({exporter=\"OTLP\"} | json logLevel=\"body.$attribute\" | __error__=`` [$__range]))"
    }
   ]
  }
 ]
}