name: ci-latest-release

on:
  push:
    branches:
      - "main"
      - "v*"
    paths:
      - "example/**"
      - "kubearmor_receiver/**"
      - "stanza_input_operator/**"

env:
  PLATFORMS: linux/amd64,linux/arm64/v8

jobs:
  build:
    name: Publish otel-receiver latest Docker image
    if: github.repository == 'kubearmor/otel-receiver'
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_AUTHTOK }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform=$PLATFORMS -t=kubearmor/otel-receiver:latest --push .
